CREATE TABLE IF NOT EXISTS users (user_id TEXT PRIMARY KEY NOT NULL, rfid_uid TEXT NOT NULL UNIQUE, full_name TEXT NOT NULL, department TEXT, status TEXT NOT NULL, created_at TEXT NOT NULL, employee_type TEXT NOT NULL DEFAULT 'INTERN', daily_rate_centavos INTEGER, payroll_profile_id TEXT, photo_url TEXT, revision INTEGER NOT NULL DEFAULT 1, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS attendance (attendance_id TEXT PRIMARY KEY NOT NULL, attendance_date TEXT NOT NULL, user_id TEXT NOT NULL, rfid_uid TEXT NOT NULL, full_name TEXT NOT NULL, department TEXT, time_in TEXT, time_out TEXT, status TEXT NOT NULL, source TEXT NOT NULL, notes TEXT NOT NULL DEFAULT '', revision INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS ux_attendance_user_date ON attendance(user_id, attendance_date);
CREATE INDEX IF NOT EXISTS ix_attendance_date_status ON attendance(attendance_date, status);
CREATE TABLE IF NOT EXISTS audit_logs (log_id TEXT PRIMARY KEY NOT NULL, timestamp TEXT NOT NULL, event_type TEXT NOT NULL, rfid_uid TEXT, user_id TEXT, message TEXT NOT NULL, request_id TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS ix_audit_request ON audit_logs(request_id);
CREATE TABLE IF NOT EXISTS intern_grace (grace_id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, week_start TEXT NOT NULL, attendance_id TEXT NOT NULL UNIQUE, used_at TEXT NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS ux_grace_user_week ON intern_grace(user_id, week_start);
CREATE TABLE IF NOT EXISTS payroll (payroll_id TEXT PRIMARY KEY NOT NULL, attendance_id TEXT NOT NULL UNIQUE, user_id TEXT NOT NULL, full_name TEXT NOT NULL, employee_type TEXT NOT NULL, attendance_date TEXT NOT NULL, actual_time_in TEXT NOT NULL, actual_time_out TEXT NOT NULL, computed_time_in TEXT NOT NULL, computed_time_out TEXT NOT NULL, grace_used INTEGER, late_hours INTEGER NOT NULL, late_deduction_centavos INTEGER NOT NULL, base_pay_centavos INTEGER NOT NULL, daily_pay_centavos INTEGER NOT NULL, notes TEXT NOT NULL DEFAULT '', revision INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS payroll_profiles (profile_id TEXT PRIMARY KEY NOT NULL, label TEXT NOT NULL, payroll_frequency TEXT NOT NULL, standard_working_days_per_cutoff REAL NOT NULL, incentives_allowance_centavos INTEGER NOT NULL, special_allowance_centavos INTEGER NOT NULL, special_holiday_multiplier REAL NOT NULL, regular_holiday_multiplier REAL NOT NULL, half_day_fraction REAL NOT NULL, overtime_rate_centavos INTEGER NOT NULL, revision INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS payroll_cutoffs (payroll_id TEXT PRIMARY KEY NOT NULL, employee_id TEXT NOT NULL, employee_name TEXT NOT NULL, payroll_profile_id TEXT NOT NULL, payroll_cutoff_label TEXT NOT NULL, cutoff_start TEXT NOT NULL, cutoff_end TEXT NOT NULL, payroll_frequency TEXT NOT NULL, daily_rate_centavos INTEGER NOT NULL, standard_working_days REAL NOT NULL, actual_working_days REAL NOT NULL, basic_pay_centavos INTEGER NOT NULL, special_holiday_days REAL NOT NULL, special_holiday_multiplier REAL NOT NULL, special_holiday_pay_centavos INTEGER NOT NULL, regular_holiday_days REAL NOT NULL, regular_holiday_multiplier REAL NOT NULL, regular_holiday_pay_centavos INTEGER NOT NULL, incentives_allowance_centavos INTEGER NOT NULL, special_allowance_centavos INTEGER NOT NULL, total_compensation_centavos INTEGER NOT NULL, total_allowance_centavos INTEGER NOT NULL, late_units REAL NOT NULL, late_deduction_centavos INTEGER NOT NULL, half_day_count REAL NOT NULL, half_day_deduction_centavos INTEGER NOT NULL, absent_days REAL NOT NULL, absence_deduction_centavos INTEGER NOT NULL, overtime_hours REAL NOT NULL, overtime_rate_centavos INTEGER NOT NULL, overtime_pay_centavos INTEGER NOT NULL, manual_adjustment_centavos INTEGER NOT NULL DEFAULT 0, adjustment_reason TEXT, gross_compensation_centavos INTEGER NOT NULL, net_pay_centavos INTEGER NOT NULL, signature_placeholder TEXT NOT NULL DEFAULT '', calculation_breakdown TEXT NOT NULL, approved_working_day_overage INTEGER NOT NULL, status TEXT NOT NULL, finalized_at TEXT, revision INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);

